### ISSUE TITLE
precise-lite version

### ISSUE THREAD

**Issue by JarbasAl** [hanzala123/jarvis-model#1]
hello

the .net files are not available, but if you still have them and are interested i can convert your model to tflite and add it to https://github.com/OpenVoiceOS/precise-lite-models

**Comment by hanzala123** [comment]
HI @JarbasAl 
Unfortunately I don't have the .net files. I have been out of this AI voice assistant field for quite a while. It didn't feel like it was worth it. Everything Mycroft could do my phone could as well with quiteness as i work late nights at home. Also it was kind of quicker to do it by hand than to speak it and then wait for it to do it. Which would obviously not work 100% of the times. Also the interactions felt very unnatural as well. So I stopped with everything put all the hardware in a drawer and forgot about it.
